services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.2
    container_name: loja-redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr=internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr=internal://redpanda:8082,external://localhost:18082
    ports:
      - "19092:19092"
      - "18082:18082"
      - "19644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.8.3
    container_name: loja-redpanda-console
    restart: unless-stopped
    depends_on:
      - redpanda
    ports:
      - "8088:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
      REDPANDA_ADMINAPI_ENABLED: "true"
      REDPANDA_ADMINAPI_URLS: http://redpanda:9644

volumes:
  redpanda-data:
