apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-service-config
data:
  SPRING_PROFILES_ACTIVE: dev
  KEYCLOAK_URL: https://dev-auth.lojacloud.com.br
  KEYCLOAK_ISSUER_URI: https://dev-auth.lojacloud.com.br/realms/extranet-realm
  KEYCLOAK_JWK_SET_URI: http://keycloak.loja.svc.cluster.local:8080/realms/extranet-realm/protocol/openid-connect/certs
  SWAGGER_URL: https://dev-api.lojacloud.com.br
  SPRINGDOC_SWAGGER_UI_OAUTH2_REDIRECT_URL: https://dev-api.lojacloud.com.br/api/loja/swagger-ui/oauth2-redirect.html
  PAGAMENTO_SERVICE_URL: http://host.minikube.internal:8090
  KAFKA_BOOTSTRAP_SERVERS: kafka.loja.svc.cluster.local:9092

  DATABASE_URL: jdbc:postgresql://host.minikube.internal:5433/lojadb?sslmode=disable
