apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-service-config
data:
  SPRING_PROFILES_ACTIVE: dev
  KEYCLOAK_URL: http://dev-auth.loja
  KEYCLOAK_ISSUER_URI: http://dev-auth.loja/realms/extranet-realm
  KEYCLOAK_JWK_SET_URI: http://dev-auth.loja/realms/extranet-realm/protocol/openid-connect/certs
  SWAGGER_URL: http://dev-api.loja
  SPRINGDOC_SWAGGER_UI_OAUTH2_REDIRECT_URL: http://dev-api.loja/api/loja/swagger-ui/oauth2-redirect.html
  PAGAMENTO_SERVICE_URL: http://host.minikube.internal:8090
  KAFKA_BOOTSTRAP_SERVERS: host.minikube.internal:19093

  DATABASE_URL: jdbc:postgresql://host.minikube.internal:5433/lojadb?sslmode=disable
