apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: loja
  annotations:
    # Redireciona HTTP para HTTPS no ingress de hmg.
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  # Em hmg, o certificado TLS fica na AWS via ACM e a terminacao HTTPS ocorre no LoadBalancer.
  ingressClassName: nginx
  rules:
    - host: hmg-auth.lojacloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
