apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-service-config
data:
  SPRING_PROFILES_ACTIVE: hmg
  KEYCLOAK_URL: https://hmg-auth.lojacloud.com.br
  SWAGGER_URL: https://hmg-api.lojacloud.com.br
  KAFKA_BOOTSTRAP_SERVERS: kafka.loja.svc.cluster.local:9092
  KEYCLOAK_ISSUER_URI: https://hmg-auth.lojacloud.com.br/realms/extranet-realm
  KEYCLOAK_JWK_SET_URI: http://keycloak.loja.svc.cluster.local:8080/realms/extranet-realm/protocol/openid-connect/certs
  SPRINGDOC_SWAGGER_UI_OAUTH2_REDIRECT_URL: https://hmg-api.lojacloud.com.br/api/loja/swagger-ui/oauth2-redirect.html
  PAGAMENTO_SERVICE_URL: http://pagamento-service.loja.svc.cluster.local
#fim
