resources:
- ../../../base/namespace
- ../../../base/loja-service
- ../../../base/redpanda
- configmap.yaml
- secret.yaml
- ingress.yaml

namespace: loja

images:
- name: loja-service:local
  newName: 950992723561.dkr.ecr.us-east-1.amazonaws.com/loja-backend/hgm/backend
  newTag: 1bd83cb59fe81aaaca01583150387510735b207b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
