resources:
- ../../../base/namespace
- ../../../base/loja-service
- configmap.yaml
- external-secret.yaml
- ingress.yaml

namespace: loja

images:
- name: loja-service:local
  newName: 950992723561.dkr.ecr.us-east-1.amazonaws.com/loja-backend/hgm/backend
  newTag: f3d7de374eae7a769d0366c17a9e9cffd271accb
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
