apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v25.1.2
          args:
            - redpanda
            - start
            - --overprovisioned
            - --smp=1
            - --memory=512M
            - --reserve-memory=0M
            - --node-id=0
            - --check=false
            - --kafka-addr=internal://0.0.0.0:9092
            - --advertise-kafka-addr=internal://kafka.loja.svc.cluster.local:9092
            - --pandaproxy-addr=internal://0.0.0.0:8082
            - --advertise-pandaproxy-addr=internal://kafka.loja.svc.cluster.local:8082
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 8082
              name: proxy
            - containerPort: 9644
              name: admin
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: redpanda-data
              mountPath: /var/lib/redpanda/data
      volumes:
        - name: redpanda-data
          emptyDir: {}
