# Valores atuais voltados para execucao local/minikube.
# TODO: mover para overlays por ambiente quando o fluxo GitOps estiver fechado.
apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-service-config
data:
  SPRING_PROFILES_ACTIVE: dev
  KEYCLOAK_URL: http://host.minikube.internal:8081
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8081/realms/extranet-realm
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://host.minikube.internal:8081/realms/extranet-realm/protocol/openid-connect/certs
  SWAGGER_URL: http://localhost:8080
  SPRINGDOC_SWAGGER_UI_OAUTH2_REDIRECT_URL: http://localhost:8080/api/loja/swagger-ui/oauth2-redirect.html
  LOJA_SERVICE_INTRACLIENT_TOKEN_URI: http://host.minikube.internal:8081/realms/intranet-realm/protocol/openid-connect/token
  LOJA_SERVICE_INTRACLIENT_ISSUER_URI: http://host.minikube.internal:8081/realms/intranet-realm
  PAGAMENTO_SERVICE_URL: http://host.minikube.internal:8090
  DATABASE_URL: jdbc:postgresql://host.minikube.internal:5433/lojadb?sslmode=disable
